# Generated by Django 4.2.5 on 2023-09-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_alter_session_options_rename_date_session_date_over_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='movie',
            new_name='ticket_movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_session',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='session_movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrators.movie'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
