# Generated by Django 4.2.5 on 2023-09-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_alter_session_name_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['time_start']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='date_start',
            new_name='time_start',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_over',
        ),
    ]
