# Generated by Django 4.2.5 on 2023-09-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0007_alter_session_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_movie',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrators.session'),
        ),
    ]
