# Generated by Django 4.2.5 on 2023-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0008_remove_ticket_ticket_movie_ticket_ticket_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session_movie']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
