# Generated by Django 4.2.5 on 2023-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0009_alter_session_options_alter_movie_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
