# Generated by Django 4.2.5 on 2023-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0010_alter_movie_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='session',
            name='date_start',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='session',
            name='time_end',
            field=models.DateTimeField(default=None),
        ),
    ]
