# Generated by Django 4.2.5 on 2023-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0011_session_date_end_session_date_start_session_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
