# Generated by Django 4.2.5 on 2023-09-30 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0014_alter_session_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
