# Generated by Django 4.2.5 on 2023-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0015_alter_session_time_end_alter_session_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
