# Generated by Django 4.2.5 on 2023-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0016_alter_session_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name_session',
            field=models.CharField(default='Название сеанса', max_length=100, unique=True),
        ),
    ]
