# Generated by Django 4.2.5 on 2023-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0019_alter_session_time_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='time_start',
        ),
        migrations.AddField(
            model_name='session',
            name='time_start',
            field=models.ManyToManyField(default=None, to='administrators.timeslot'),
        ),
    ]
