# Generated by Django 4.2.5 on 2023-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0020_timeslot_remove_session_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time_start',
        ),
        migrations.AddField(
            model_name='session',
            name='time_start',
            field=models.TimeField(default=None),
        ),
    ]
