# Generated by Django 4.2.5 on 2023-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0021_remove_session_time_start_session_time_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
