# Generated by Django 4.2.5 on 2023-10-04 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0022_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateField(default=datetime.date(2023, 10, 4)),
        ),
    ]
