# Generated by Django 4.2.5 on 2023-10-06 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0023_ticket_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
    ]
