# Generated by Django 4.2.5 on 2023-10-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0025_alter_ticket_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name_hall',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
